### ISSUE TITLE
Picasa::doUpload: Upload failed. Photo limit reached.

### ISSUE THREAD

**Issue by phuclh** [ptcong/php-image-uploader#4]
I got a message like:
`Picasa::doUpload: Upload failed. Photo limit reached.`

What is problem? Thank you.

**Comment by ptcong** [comment]
Its reach photo count limited of the album. Try to change your album id

**Comment by phuclh** [comment]
How can I create album. Now, I don't set album id when uploading. Thank you !!!

**Comment by ptcong** [comment]
Ok, open picasaweb.google.com/?noredirect=1 then create new album (click upload a picture)
Now back to picasa home page, click to your album, click RSS, you will see a URL like .../user/xxx/albumid/**your number here**/

**Comment by phuclh** [comment]
Ok thank you :D. But can I create album via your package? Because my project will upload images to Picasa every hour. I think create album manually is not a good idea :D.

**Comment by ptcong** [comment]
you can use 
`echo $uploader->addAlbum('album title');`
for create new album id

**Comment by phuclh** [comment]
Oh. Thank you very much !!!!
