### ISSUE TITLE
transload

### ISSUE THREAD

**Issue by Codez1337** [ptcong/php-image-uploader#7]
the transload for imgur is set to image shack. what is the imgur one and what exactly does transload do?

**Comment by ptcong** [comment]
I don't understand all your question.
Trasnload is transfer an image from a server to another server by image url so you can use any image url to transload.

**Comment by Codez1337** [comment]
and what is the getcwd('/ a.jpg'); part all about?

**Comment by ptcong** [comment]
Check [php::getcwd()](http://php.net/getcwd) and should understand it.
$uploader->upload('an image file path');
$uploader->transload('an image url');
